### ISSUE TITLE
增加更多格式支持|Add Support to More Format

### ISSUE THREAD

**Issue by Jiang10086** [dream-num/obsidian-univer#67]
### Problem

很感谢你们开发了这个扩展，让我能在 Obsidian 中看 xlsx， 不知道能否支持 xls 这种老表格格式。当然，要是能扩展支持 Office 三件套就更好了 （doc、docx、ppt、pptx）

Thanks for developing this plugin for read .xlsx file inObsidian, but I am wonder if .xls file can be supported, too. Moreover, it will be wonderful to support all office format (including doc, docx, ppt and pptx).

### Solution

Add xls file support.

**Comment by karlsbeard** [comment]
Thanks a lot for ur issue. Now the obsidian-univer can support the xls、xlsm、 xlsx format. What's more, u can use doc function if u create a Univer Doc. The docx、ppt、 pptx and more formats will be supported in the near future. Just pay attention to obsidian-univer updates.  We would be grateful if u could share this plugin to ur friends or give our project a star.

**Comment by Jiang10086** [comment]
> Thanks a lot for ur issue. Now the Obsidian-univer can support the xls、xlsm、 xlsx format. What's more, u can use doc function if u create a Univer Doc. The docx、ppt、 pptx and more formats will be supported in the near future. Just pay attention to Obsidian-univer updates. We would be grateful if u could share this plugin to ur friends or give our project a star.

Thanks for reply, I have shared this wonderful extension to some Obsidian and Markdown group.
