### ISSUE TITLE
Use plugin in Obsidian from mobile devices

### ISSUE THREAD

**Issue by dekoov** [dream-num/obsidian-univer#69]
### Problem

Thank you very much for this great plugin. I like the amount of formulas and functions that the Excel format brings, but I was wondering if it could also be made compatible with the Obsidian android app, currently it does not even allow you to load the plugin

### Solution

Plugin compatibility on Obsidian Android

### Additional details

![Infinix X659B](https://github.com/dream-num/obsidian-univer/assets/107126983/8430df32-f103-4d86-9844-71f2afaa3c79)

**Comment by niazlv** [comment]
I agree. This is the deciding factor that would change everything colossally and I could use this plugin for counts within my notes

**Comment by karlsbeard** [comment]
We support the Android app in this version but sadly maybe it can not adapt well to mobile devices because the adaptive function is not supported by univer at the initial stage. Hoping this plugin can help u better ur life.
