### ISSUE TITLE
BUG: Copy and paste of formulas does not work (not enhancement, change label to BUG)

### ISSUE THREAD

**Issue by gregheth** [dream-num/obsidian-univer#70]
### Problem

Coping formulas ignores 
- `$` as absolute references and always pastes relative column and row
- whole column references `X:X` and pastes `#REF`

### Solution

fix the formula copy and paste utility

**Comment by karlsbeard** [comment]
I have tested this function in the obsidian-univer plugin and found that its behavior is consistent with Excel. If you believe this is a problem, please provide more detailed information, such as screenshots or GIFs.
