### ISSUE TITLE
Crash on Android 

### ISSUE THREAD

**Issue by lynxaegon** [dream-num/obsidian-univer#80]
### Problem

I tried to install Univer from the Community Plugins on a Pixel 7 Android 14 right after installing, it crashes the Obsidian App and if you open obsidian back, you will see Univer installed but not enabled, and enabling doesn't work.

### Solution

-

**Comment by karlsbeard** [comment]
Currently, this feature does not fully support mobile devices. We recommend using it on a PC for the best experience.
