### ISSUE TITLE
help!How can I convert file formats?

### ISSUE THREAD

**Issue by alca2012** [dream-num/obsidian-univer#84]
### Problem

I like this plugin,but how can I convert usheet and udoc files to xlsx and docx formats?

### Solution

Convert file to xlsx or docx

**Comment by jikkai** [comment]
You can save the usheet as an xlsx file through "Save as".

<img width="921" alt="image" src="https://github.com/user-attachments/assets/e14a3933-90f8-45c5-bf68-741e3a840f98">

**Comment by alca2012** [comment]
Thanks，i found it. Does udoc not support this feature now?
